---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vaultwarden
  namespace: vaultwarden
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: vaultwarden
      app.kubernetes.io/instance: vaultwarden-1
      app.kubernetes.io/component: server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: vaultwarden
        app.kubernetes.io/instance: vaultwarden-1
        app.kubernetes.io/component: server
    spec:
      containers:
      - name: vaultwarden
        image: vaultwarden/server:latest
        env:
          - name: WEBSOCKET_ENABLED
            value: "true"
          - name: Domain
            value: "https://vault.prossertech.com"
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1"
        ports:
          - containerPort: 80
        volumeMounts:
          - name:  data
            mountPath:  /data
      volumes:
        - name: data
          nfs:
            server: storage-pve-02.int.prossertech.com
            path: /data/rke/vaultwarden/data