apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vaultwarden-ingress
  labels:
    name: vaultwarden-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: vaultwarden.int.prossertech.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: vaultwarden-svc
            port: 
              name: http
---
apiVersion: v1
kind: Service
metadata:
  name: vaultwarden-svc
  namespace: vaultwarden
spec:
  selector:
    app.kubernetes.io/name: vaultwarden
    app.kubernetes.io/instance: vaultwarden-1
    app.kubernetes.io/component: server
  ports:
  - name: http
    protocol: TCP
    port: 80