apiVersion: v1
kind: Pod
metadata:
  name: vault-proxy
  namespace: default
  labels:
    app: vault-proxy
spec:
  serviceAccountName: vault-auth

  volumes:
    - configMap:
        items:
          - key: vault-proxy-config.hcl
            path: vault-proxy-config.hcl
        name: vault-proxy-config
      name: config

  containers:
    - args:
        - proxy
        - -config=/etc/vault/vault-proxy-config.hcl
        - -log-level=debug
      env:
        - name: VAULT_ADDR
          value: https://vault-internal.int.prossertech.com
      image: hashicorp/vault
      name: vault-proxy
      volumeMounts:
        - mountPath: /etc/vault
          name: config
---
apiVersion: v1
kind: Service
metadata:
  name: vault-proxy
spec:
  selector:
    app: vault-proxy
  ports:
  - port: 80
    targetPort: 8200
