---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin
  namespace: jellyfin
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: jellyfin
      app.kubernetes.io/instance: jellyfin-1
      app.kubernetes.io/component: server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: jellyfin
        app.kubernetes.io/instance: jellyfin-1
        app.kubernetes.io/component: server
    spec:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: node.kubernetes.io/type
              operator: In
              values:
              - gpu
      containers:
      - name: jellyfin
        image: jellyfin/jellyfin
        securityContext:
          runAsUser: 1001
          runAsGroup: 1001
        env:
          - name: JELLYFIN_PublishedServerUrl
            value: http://jellyfin-svc.jellyfin.svc.cluster.local
        resources:
          limits:
            memory: "8192Mi"
            cpu: "4.0"
        ports:
          - containerPort: 8096
          - containerPort: 1900
          - containerPort: 7359
        volumeMounts:
          - name:  config
            mountPath:  /config
          - name: cache
            mountPath: /cache
          - name: media 
            mountPath: /media 
      volumes:
        - name: config 
          nfs:
            server: storage-pve-02.int.prossertech.com
            path: /data/rke/jellyfin/config
        - name: cache
          nfs: 
            server: storage-pve-02.int.prossertech.com
            path: /data/rke/jellyfin/cache
        - name: media
          nfs:
            server: storage-pve-02.int.prossertech.com
            path: /data/media
---
apiVersion: v1
kind: Service
metadata:
  name: jellyfin-svc
  namespace: jellyfin
spec:
  selector:
    app.kubernetes.io/name: jellyfin
    app.kubernetes.io/instance: jellyfin-1
    app.kubernetes.io/component: server
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8096