apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tools
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: cloudflared
    server: https://kubernetes.default.svc
  project: default
  source:
    path: infra/tools
    repoURL: https://github.com/drewjprosser/home-argo.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true