apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://helm.releases.hashicorp.com
    targetRevision: 0.28.0
    chart: vault
    helm:
      releaseName: vault
      valuesObject:
        server:
          ingress:
            enabled: true
            hosts:
              - host: vault.talos.prossertech.com
                paths: ["/"]
        ui: 
          enable: true
        injector:
          enable: false
  destination:
    server: "https://kubernetes.default.svc"
    namespace: vault
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true