apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: giteadb
  namespace: gitea
spec:
  instances: 3
  storage:
    size: 1Gi
  monitoring:
    enablePodMonitor: true
  bootstrap:
    initdb:
      database: giteadb
      owner: gitea
      secret:
        name: gitea-secret
      localeCollate: en_US.UTF-8
      localeCType: en_US.UTF-8
      postInitSQL:
       - CREATE SCHEMA gitea
  postgresql:
    parameters:
      password_encryption: scram-sha-256
    pg_hba:
      - host    giteadb    gitea    10.0.0.0/8    scram-sha-256
