---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitea-secret
  namespace: gitea
spec:
  encryptedData:
    password: AgA4Zrxoj8k2Drp7vcBq1R32a3O9sTKUgxii3x0iW7mExZ1T5jxJqjbgLEQNIp/PSPHap3RyFW/ECkZ7QCDIcT+hgimj4lPCkCH5Q2lwdWF5/qn7Lpu4OmoVjam22G6Cp6BPZWkIe59p7lbfn9M324AgkBMNyMAzUyVBPoL5lrH23Ua27OfvzMsCGcwTMcO02ow9lrKOiCrK3dxJhkqTIaPCeXdMEZ7gzjtabrebymZznU8y8i7n9atrm4Ax98yLQ5B3AcTce0ya2xVEjWiwfWHH/9d89U9Bc/EhDNYAtqbulrii7IgwlRuktWEKr6UDQkRBiQvUEJFTnPtPN30ePzt9U0kWHznbbhXXmKFhRsVD2DfFcmvDJ4G65kSrufBoDfap7WYdBVKDzQ1ytCv8qWQfNtetzqtxTCxyycq+EcRDtX54LlcdOBCjeskra2q03gHM8Mfx1SSuqCNfHzgUYOc/8jg9IqS6vvwE+gRLjWCaxg8C9Ce9tGDYRteFaOZqc+VuA4mLOaYFKZEvg5DaoKCcBl0vy1zzFfqGvHJ+I8WPZKAZGWtE/aLwdwsCytt9l4lTTQQEWDzhNEzABXhFC9h8Jsp6pKTg6uwGkOj0pSVmsOpLT3pSFeEdpJ4IpPFfTm+PO3yFOnf1QabpucglO/uPdql+8wkTxY8UergfgWT4tVbBsb1Y1LS+mcUZvn0imAgo0VFgPr3+Lx0LTrlj
    username: AgBpLl3mYAKqsAL3MWZjwYRgZQ83tzSQNPHHHHRqDjPuqZ+cz9jS9VABy990h3yVQ7rnI6wSdfWJRvgYalle0HEVWbFN7P2eFjaU7gOdjyzYZ3aecG2TFi33tzS2FpeU7z4m4WgSbaMEaS7h1uX7uBN9JjsxXjJjpOJgw8HrFP7moZxMDELcV9QFYotxor/7MwtGcKIqSQJf5yV6aaYDBFkie/alsGz3Dv9ejzBHkOIWsxuDIB4fXwuYMlZzM5dNQ555YHC8H+Bpw4MLqH6F6XvPsqhte+QzzevSmIVVwY23Tmf1O8uHieNvjLfx3i+oqOnqq4+7+qCtY+wUOOygZqNqcpTZnQC13GqrSZOBryqWaU3WEG261xMwYPNv+vvWHid/fyyh+hXdR2+j9YR6bJbULjBXONLc8ioGBr97yQwnG1MotQlFsrbhZdsnmVdPKZUUSbW85hlH25NKloD+SZigwoWi6xMQL8IK3Jz7CNkwLdQO9DN5bt1OGN5/VXRKOzFdGMieUknyCY9Kg+bDcnkqp9IeVJlCkj/+cxS+bsKMxVInGVF1eWiAzUycn9eLXVUXAF1TF043cuS030rg3WxZFxc/FbdmHzoMIfziRtyc6ebvkCVANNsGv0/TfF/4ePMblgWVZRl+1V1AT3IQeZT1M0f8knrQmeEDN8RpRWI1xaxr6CJ9eaJyQRoYda7wdP3W7E6d2Q==
  template:
    metadata:
      creationTimestamp: null
      name: gitea-secret
      namespace: gitea
    type: kubernetes.io/basic-auth
