apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster-example
  namespace: default
spec:
  instances: 3

  storage:
    size: 1Gi

  monitoring:
    enablePodMonitor: true
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cluster-example-rw
  labels:
    name: cluster-example-rw
spec:
  ingressClassName: nginx
  rules:
  - host: pg.prod.prossertech.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: cluster-example-rw
            port: 
              number: 5432
