---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitea-secret
  namespace: gitea
spec:
  encryptedData:
    password: AgAQUn8yX6D0XyQX0MHLZqdy4DBa26WyS2cSmDgbk6QmfotuXV2eMeTqZgUG3ufhywTri06SnehkFARyHovZ4W7U+Lsl8iOxYDEyZsKOZvTLvVRsHIMv+pn/+q4xLHX+QlP3S8AOaEXe5wAPCZozkRKK9NI7wdEh/aZ3hTRpCYgbEvAHjwqPSZCsnzoIxAchzhe1MUex1UhbeJinCjSYvIXMuyizueVChKw5QSM8ByLOx/pxOhJC1kQfa8gDjS9ofObJ1UXtQBcFrak5IEtB94vxMIdUxukNtSQf9dpNbnWqcXx0aqeAGZ9VAd1Rdpl5V5T8sG3692u4qgAOaoAeFpzEAe8lC4Owj+q4JnmRyILV5jCJ/2Bpi9QPAizHG7zusFAjfcursis7rq+jHBYUMKzykYsezGpKduxGKXpdytcTFVePxt19H509z8t0G1zwgAXSoJbCmnUAOhu3/meea7ih7wvZoSr3xonShRZUZGzAtx8N8q///yI3+j6zZWSiCT0sZuDHRyRtABqOJhOcCl44An/Q1aYuhQgNS1A4umMYe5fm8tOf3yllD0P0k2oZtnwAAD8YPXZdajvJyIamLxKoVdMXurwL5wqS8N8+eZVzfoKtDmuM/gHnkTcKyuW74l1bU9nbCPe/uVj9efEVFPDtOofDgSa7BFi/6bicwuEobkG+fhy/Y5SDSKUzwYfrGEHWDKnvu0U4LX4MdvwB
    username: AgCPCrHHPaNuEfj/Kqal/WevgF7dXcXFsLkqooMnHZWixY5SehtgSxd6sln9XuEe0iavLihhjtiX54HVV1HfGA1nLDPDvCLVVmo0N6IgOClYQMwlbMrXOnRK0Dlty+CehX7thB9IwF+HYRPlp60e3/0WggYwIsrXiBe2x+pmKmE0rMAX/QiNXCoGFA7Jxbg6hvYhf9dsx8nkV+cX0GsZpEXg7zS6NrtWUBhw/GV9jbRqBE+N6MAoMdKJ9f6OwOvdlZbIVKNZjwDjMM2GQgabuUeRrkUKEEmlFxZYJ3qMkUhZgkLJ/zAq+6DSfoFoKF3c0UINGlsSBt6fvKXC+oaDmhFGhEo6f+M76Kg508q8vhlM2TsVf7UHM1M7J9a5TK007N5QF0hd0HGclf2WmjHbAEfrPxb9XxFqu+1aORJuBEwFq4vPAsUDEnXCToEzQZKWP8lg5GnucP+8jJvRFj6t8L1r95ThP/FqtsnI3BYXgElWd3wwyFZyYKq1UpevDYANrKJsmzFTwlb9mMpkM9cyUBYc8vwh48+SQey1nXIxFV1NGRQqqimBfLch4dJPpKnzpBH2QvDWpEI6hvgXJgaP+VAy37JsS/3xxQEf8pUyXbOwtNyMitWDgFmzIR8GTLpSjPDgUGqfLPpb9161w6RjpwMnRfi+AtFsX+SE/Q6y89QKE/oyP2rMQJbsHmbSjvoOjlnmuHN20BM=
  template:
    metadata:
      creationTimestamp: null
      name: gitea-secret
      namespace: gitea
    type: kubernetes.io/basic-auth
