apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: terrakube
  namespace: argocd
spec:
  project: default
  source:
    chart: terrakube
    repoURL: https://AzBuilder.github.io/terrakube-helm-chart
    targetRevision: 3.17.1
    helm:
      releaseName: terrakube
  destination:
    server: "https://kubernetes.default.svc"
    namespace: terrakube