apiVersion: "cilium.io/v2alpha1"
kind: CiliumBGPPeeringPolicy
metadata:
 name: 01-bgp-peering-policy
spec: # CiliumBGPPeeringPolicySpec
  nodeSelector:
    matchLabels:
      node.kubernetes.io/bgp-policy: a
  virtualRouters: # []CiliumBGPVirtualRouter
  - localASN: 65001
    exportPodCIDR: true
    neighbors: # []CiliumBGPNeighbor
    - peerAddress: '10.10.10.1/32'
      peerASN: 65001
      #authSecretRef: bgpsecret
      eBGPMultihopTTL: 10
      connectRetryTimeSeconds: 120
      holdTimeSeconds: 90
      keepAliveTimeSeconds: 30
      gracefulRestart:
        enabled: true
        restartTimeSeconds: 120
    serviceSelector:
        matchExpressions:
          - {key: somekey, operator: NotIn, values: ['never-used-value']}