apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: applications
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/drewjprosser/home-argo.git
    targetRevision: HEAD 
    path: apps
    directory:
      exclude: 'values.yaml'
      recurse: true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: argocd
