apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rook-ceph
  namespace: argocd
spec:
  project: default
  source:
    chart: rook-ceph
    repoURL: https://charts.rook.io/release
    targetRevision: 1.14.5
    helm:
      releaseName: rook-release
      valueFiles:
        - ../../values/rook/values.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: rook-ceph