apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-backend
spec:
  provider:
    vault:
      server: "http://vault.vault.svc.cluster.local:8200"
      path: "kv"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "approle"
          roleId: "268f08c2-d2c8-0b57-1db9-cfeabe8bb4f6"
          serviceAccountRef:
            name: "vault-auth"
            namespace: external-secrets
          