apiVersion: apps/v1
kind: Deployment
metadata:
  # This name uniquely identifies the Deployment
  name: busybox
  namespace: busybox
spec:  
  replicas: 1
  selector:
    matchLabels:
      module: busybox
  template:
    metadata:
      labels:
        # This label is used as a selector in Service definition
        module: busybox
    spec:
      containers:
      - name: busybox
        image: busybox:latest
        command:
          - "/bin/bash"