apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: idrac-fan-control
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  destination:
    namespace: idrac-fan-control
    server: https://kubernetes.default.svc
  project: default
  source:
    path: apps/idrac-fan-control
    repoURL: https://github.com/drewjprosser/home-argo.git
    targetRevision: HEAD
    directory: 
      recurse: true
  syncPolicy:
    # managedNamespaceMetadata:
    #   labels:
    #     pod-security.kubernetes.io/enforce: privileged
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true