apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared-internal
  namespace: cloudflared
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  # restartPolicy: Always
  selector:
    matchLabels:
      app: cloudflared-internal
  replicas: 2 # You could also consider elastic scaling for this deployment
  template:
    metadata:
      labels:
        app: cloudflared-internal
    spec:
      containers:
      - name: cloudflared
        image: cloudflare/cloudflared:2024.6.1
        args:
        - tunnel
        - --metrics=0.0.0.0:2000
        - run
        env:
          - name: TUNNEL_TOKEN
            valueFrom:
              secretKeyRef:
                name: tunnel-credentials-internal
                key: token
        resources:
          limits:
            memory: "1Gi"
            cpu: "1"
        livenessProbe:
          httpGet:
            # Cloudflared has a /ready endpoint which returns 200 if and only if
            # it has an active connection to the edge.
            path: /ready
            port: 2000
          failureThreshold: 1
          initialDelaySeconds: 60
          periodSeconds: 10
