---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tunnel-credentials-internal
  namespace: cloudflared
spec:
  encryptedData:
    token: AgDaqZzmBxXvLi7YT+BsRcG0zZeeUvfDN2hBaxAZuclhqvf+icEv7uC7OWz942C/Mv0heaW88vmy10kzfrjK0mr9psnyXPd1wTzf+Wvy7Xt42CIdWZsl+3Me4uFfD0rsK2KeuBB+tlZ88UfgIA6XpsEZPXfd3THp3Jg5XSHJlpvtEE/SSaAkRwzOhNqp8XUE6K3G3POHRK+rIXu0/4mV7aRlbv83ob64ViN9i6jcY+5pcvCkeuEDAyLnyFVNrhTtyCENBumW/PhgwjNH5OaY1w/Kp1ygN8smhVmOHdzEGEaT/VEAJDRGQtyhqX6BqpsuGHYi1PtNazM2luITFgiHiAXe2PGkTUtHt3RAlFJFLPPBsQd6kPejDAz7a47nQwgnROTTpOWWVKiKLFZASOP0j36mjG9pNTvQI3r33M062dUIUAVQLRKnWsZmy3EcceC0IpNvX2R7nCoAs7ZwtHln+9fXTSERsvvh/GrN41zM7RvVQq0ol43RFlK2tRi0xG5y5buSBE9iIe1vHokWL2VmfxmHTOIvttMq8ldkj0/jAJMUdZ6IIjTf4QjWyeJhbQrQ3esp60mLXOuKlXTBAvlE6jgjybYiWySSb2pq5VZtIf2IflYZdgeddGGUl3z52eGqTHCcG4pSlvFZvy7LMD/VdlJrONRwxOABAKDiGhb4essmJ5OZAJzS8epom8mVQu8k4iCRl1ASspq1n5BZ7qU4Vc+4FBxgU4yABKtLDe+p/agX1M5sXSnvINc8gyIYw4iJfqKduTyGfPdGK20UyVTph9KALUi0L3ty3t2UyUYcT5K3HhJWUw2aU5zq4inQjcuYzYtx8VSvOI8UUcGjcn7gy++qxq+yEnFbMfNdFPm9JdzkhLuwuiRjPlMTDuYyQvCKBVydDXq+h50QfLCj9QhLTY/3zyi71uYHWoD8hamsWRN87YpMqMIF7Ali
  template:
    metadata:
      creationTimestamp: null
      name: tunnel-credentials-internal
      namespace: cloudflared
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tunnel-credentials
  namespace: cloudflared
spec:
  encryptedData:
    credentials.json: AgBYVI5pN1QQo/BArwbIENe+eDiB3/ysx2vepDd5Om0HHsGy0nzTszKNPsdIhQ/cru7j2FWKA6CwUiQq6sX3KxkPA2RVKqL3WNAOzIc8SsBsEKASStihuCy9FMhHBAkOWxZkP6611LIN3fvXrRGqhT1pYFdtrgCM3gsO3UpIUpu9F55NnqMo2P97tKbYkdbCp3brYGPvt/dIeiABRmYKSSuTrIXpS06p5WT+btQYcBMPNWlTrdqkUDJ3jJuLKrDmmTKRPhIoBnQb2NzTLZexTXBz/G8fBQLpX1ZliQ2GqiLM7yOXhw8hzwVG5FXFfSj1YNUq4PDBuw1ISCUzPkiUV7moFzlBn4SRAs6G3PJxg/8TEd2/pax+mDxWQoGPdwWCBh+VNlmdyOP8bsWa4LbCFnQjL+vG2lJ+s3eQiGb63AAHrL9O33Hv0ywdQyXaFanmyhe6A0zrCotbbSpZzZTvvJjVrrnrxU9Vta7xgRpMFEBkQlI8Z3Hoo5dsnGjxj0MsIs92LF4aIdz00HRppNSf5m6FV7o8G8SMnVAAhutM2Cyo9ZLs9YjqG6jyVDag+4xmAcBNT4H3JKcvMVT95EKLoYu/HYHdxvrsXduxQj75SaF8BEfEVaFjViLBWRCvJCCR4MKEkx66d2J+SkVwxkxM8THAsh0TwEJ6nmHSbOntCBm1xyGde+dGO/2XH/9NVd827jgI0axk86Gdq0EjpyPBHCpL70lGiGD5nkOja+QA38+d+Df/o9IC4yDoOD6w6S790WvtaAhBU97mDfxAltlT/ugJNKvNR3KLToumZrTwe5jVuCZHO3+ZLYpPwJNDRqx7YfFpQo60IxvYEAPraLYtHs/IerV0ZQCXG4hN23Y34TA0kdSHYLrp+hUxBSPHry6MXMRURy/hbq1GaJ+xiDBQMQvUmA==
  template:
    metadata:
      creationTimestamp: null
      name: tunnel-credentials
      namespace: cloudflared
