apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: argocd
  name: argo-cd-ui
  labels:
    name: argo-cd-ui
  annotations:
    ingress.cilium.io/tls-passthrough: enabled
spec:
  ingressClassName: cilium
  rules:
  - host: argocd.int.prossertech.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: argo-cd-argocd-server
            port: 
              number: 443
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: argocd
  name: argo-cd-grpc
  labels:
    name: argo-cd-grpc
  annotations:
    ingress.cilium.io/tls-passthrough: enabled
spec:
  ingressClassName: cilium
  rules:
  - host: argocd.int.prossertech.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: argo-cd-argocd-server
            port: 
              number: 443