---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitea-secret
  namespace: gitea
spec:
  encryptedData:
    email: AgCs6BfJI0vXA6HVoieUF2q/oNG1bsgXptrTZheRLvIEgWkvTrqIOaghcrN0VdzWN5XqANfUD2UMJmPOmh9Vc/Mdb8uD46QPTwgqyKzJajF0b5pOvqYHa29iAmoOMQq8Uxa+tKkaoQkZpbwC108gcF2LzXbbouc1oWpE5Nz7TIHQn0JHELAyMYm/WmDvL7u2uTeO0iPKbGByBmvtpRU4uMQErwTPeSYa0/bEMevwuv+ntURtTVWcRqGV8Mr4IGQQJG5DS+mr1IuiaQy5kpGobApNThhEwKrZo0IAqDQAqQasmw72OWgLQFF6F1NELq4jgAXuHOVQfBgL/uXf8zMMI/m6q9wvRytwuzzEiO6AdAqpyasqnp56rZJ2TGsVh0ytAjTTi4UjjPpYEoUCX8luwFlKBL2uitsqU4kRh2ybznAcCq8mxUcgmlQZf7ABMXbh2lPvxzGMQghQmeExFOvGdMgnrhWk+8UyQmMBvD1k8z0C7NsZGbaKWG07NUubYlu9qO5iGc48BaiQedNmGgNUr9s0IfSeL8Q/HOf50Ku7QHXs0z2z2Lcay3GIHBGy5p5p3M5UK6GkHPcfqjaTtSO0/oYjVOIboREfvO1+jOMaunA4HGWe4rkYVxyySCvZVIuWxfWvdyILq+AKy+DZp3OfEB5gBRkxF2yKafQYuGlBv0UoyVJX6P8kk/zeb9TnzOq8r21AdEZz5aoFzE7252p98SZ/IenxhS9J
    password: AgCnrtPCvpsqePv2ocrF5Gl2z3y4vPY70tYa3PuO3KKvU/VQpoW53DGoT9o9KG5pxd3eHaJ8tpm4lX1ZsPaY+40bkTQ5D0ZPq+U4W+55mxkTPhuTVWw0iwxiqQrHfxClQndYLIHmDjPFj2dsdvL7cYZixTiAhu/0f0F+hmvfgtMTatGlgYosMVkT1HitjcpMUsuCNa6bb3/tjXyUoblO3hr8bpol8M38MyhIOQc1oqdGJ53muRkabniEjQK4pxXkAU7CPVpPw5Cc7Z55CMvvJj4bW/Sog/usnMueNoxWl99Gv7fV1OUb3HK+QkixWKwjtb26RE31ArCn1EI41cLfeZrufo8zH6+m4brMl+VYG2vDX4WJYhzQhKq1dzX4OZKNwZeiMAVBOVSXd59N3jaMT32+KULx8Al626uAkE0fSJvob2A+rKsIeKkuD8XsI8Bgz16Mbk/7XTqs0wg6IZIuBuyyDYXMLQCJiUyuQzCOvD5hEDhMNCNTlZkLxapb+PSWQRc1WX0iSjBYTJJLz0duv1s17E0A10kK4OL4/VKyU2RhbxQAqcKGhzJsBeyAq3yGqST3mumuOhBHBFlsw2urUZaz/WdwAcAdPMd5Xz8QEnQ7PKM/ioA7lOatmCXrx4hxTjoJXQ+LtVvDedkvnZD+T2EagDC5QSgkzH1BxQMQJf+TRaRAwl9QZqHK/E4Y0YMvqmwNpTZSkpgH/w==
    username: AgArhzgSXV9VF1o7TQR8rfHvIKS29WeZQ5vqszEOuq2Yq4GQVp/qWPC0Ep9wb0ohj1z8unO6pVkESuzGD7/hKGbDDOQHtNXWmVg/zUZdGBak+je3B7+LUKBI6Cm+Wj5NaWHOzMtJ4/ZltiBzF/HUkI+IdHBzxL47kHx6CO8IIW7NKqEBZ0/afHoRyB3V9RoxgzERu/oVTsPK2k0g9y2l7Yzak5vAGc/zvTukseAjWgcNarVpDFOCoAiiRRBUMiuXXdftaQcYlR5AXuj1mo524mkUt4BP0KEWbWVh0UJtPm3Btbolc5nnxBGbCivdTVyqnTmK1HJUppVWcVQSS0MVpU2+2g0wk+n/WfIJkaHLN1GzhUJE1xUmJJ9V7o2n7ie1LES42VwFcxLM0bKlD9NGcIdw9PdQQ7IJu3seyR3py2gPEUtFn47qdx49+5zTb3gwUNqJ6PP5v0/Oq/AoeYq2n2INDRCj7AWGPFaOpmMS1a0Mz8WWckjkeeQQfQSrLTEfU0nMzW2XFpQ1KYuTckO3bnOW5/lxPTCLKjldxXyEmeRTnKslYAFiE1L1pr0d0z+8skAToEHuUNwrqcJLK0RqocFTZQ4y7/eLGIU/xq9Csi1Bpmsvh6B3qUzW10XM+k6ge2fX9rhedzS3/icfGBj1jbE6krdBGyFzmdMda0Twz/D3QiVqveQYalwtAkeTTRJRe/pXKPpmkdKH/g==
  template:
    metadata:
      creationTimestamp: null
      name: gitea-secret
      namespace: gitea
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: runner-secret
  namespace: default
spec:
  encryptedData:
    token: AgBXYm8FQ+gt8F1MOVYeySzubLCQGZySjJALv6+Y3Gr4BKiKAUlLw4tBYmcy5ZXYjaUQ6mL1Opz19oE5IZxIeYEG+7iuNNLXXN/HixP8Y0oS+YvWTjrZ/+oTqPMK1OTUDLN0OV70WXPQ1wj3rBu5U+rLGMTy1vDUNbJDnainHMYgWX0YxQQ7tnwTdvxZftlqqWUiWa+Drk4RD0tsQ5Rtu+aDjecGBgkUflmsKb/PQtcQvzlnqBcRPGMWaUtKJef+V3heoiD9tcPiYWyE7kA+JIkw2nZo8Qblsnr9Y2KbqVJV0XHhAGgBaEXVkDPbd7P4qcFFn5yUgW/JJtJAxolzzrqurjRHVoNGPcpyFqqMqZJ3KC31puuwzsdjnDpaFGO3bF4GAOvVnDcjusoM/KVuDSlSXcBFYq8gRLm2iptXPDaF/TcK5S1dJGdUdWIW5ERxjEB1HSHPJ+ySqBVYxCtH2+wm4UVe4+a6coXLe5ZsQqzTZhBC/4HClJOMUBkEjUdA/m+jbNptCO7M3fObYAHuAdqQmIR6dTNBNR9X0NX0pLdEe1CjWfMMmyUVuTEIlH7fHwd2rxd1WwXKIXTmLDmbOFoxkDppwqzXUDxPRd59qW4G8HVxp56eMJjR+imQnBpmY1ULc57oX0OfRrCiwYRaUPeXl6qH0wpedKg4tZAuZ5zujoPfEZhw8FxonCekr9NOruZ8hRjA7h06AsMe+l2wyrJZafUVH0n9Jngwx+FhPuM=
  template:
    metadata:
      creationTimestamp: null
      name: runner-secret
      namespace: default
    type: Opaque
