---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitea-secret
  namespace: gitea
spec:
  encryptedData:
    email: AgC/EIuzxpuHz6//iqf9kBjbCQQ5ur8e+ZpeGhneF+TnWx0arP8UjCx790Guf06JO11yiXbZcKMRRXobURyFSDy/5FZqojy3atgWmEQS89dONOxud3aCOHbxLLvS511UCJJQJXphj+3AwWqD//0w+kmNTEecJFdlqSF2TJMxWP5rH4NKH1WTdC3Iv8SMPCHT2KEXa9fXP47AX3EEHzxMfyA7tPxuimzUL1S+y8+akxdbbraOvFpYmusMTZCQsLdf/Fi3OzeeX5ZpmaWZrlRAgyvFI+rTDrBCQHT3ertdnylWUif2YKoKovL1WqmTHRPNzzJoPT4Ptzc4Jih2e2BBrvlPLHpYMiQHRdIlims540oH7Zqs4txdVGWlolNCTDmVhEoF0iB2Cj2ifs59pKfofwfsTLdCBEEHEsZB5rKRH9fHcxAzIpB73SA5hHWAudzVOh5zqa0Db52JruYWOnCz+ZaM5LJEmDO8QgsZ08r9DET6R9fwamJC/7votUbjqjtAzwin+bvfQTpKd6nM38/vPmf02IkVjvniFJBDsUxRVanAibHiYHrVueKCqkJApOi3UvmUbFiB+h7+QV08QHAnPQfPdJYKHmCzM3dvdEonpgfDaGaWDIPA6517fAz6G7nul5t37xtTZ9V9VjGpMYKEv/YRoKSk2V1QpnLwHljJ0sbifqEyZ9EbuLeVNvwM8CHGBgTx9j51lS7kRMGP7O96bmCEuF3r4kpG
    password: AgBTuCvUBzJbubskDu5O7FFv4SJRvLsgMg5nwu2mOmJ8V7UnVPSCejWpPZi4HxsqatroL+rdxTkUsLFcBM1gxDqcV2fobha81AF1vs49WQ4ECnZiRMWmSGsy3hQIXfwgq4x57rARFkNsgInc1pyh53+tbiTM186GeA113d5Zr3ZFm+WbX+L9Rh4axKUj93kV0EwotEBXiuLGm/DUcXsyWkq5m7XwORnZ0ivz0QC9yYBxwzBWPubn728Y2iso5bGBsF6RJpeHfyDkMFGnu47yOVKgHMfKRKaKIFvyzMBvX3Nh+scEr09u+rxSmPN12NyvY3Seyxbzmy+3h3PWdvvz5w1Vql+NDr8a3e/Ey+PxE40zGEvCqtNmgL5ausy8frPZ0xEt0MALGxaf1mxX84sagpjjiXwaTOEQoiXUWd6VcbiiulpaFT7ZIK97/pkP3oUMcXDc7X9fY7znhe9ZEdN5qdl/FXeZ5cozMnf8LICaelFndH+chB/2B/VXmuLsCpXuPtEvna6mvDw9f8gGd7T4LVQxe09LhkOhRYJQkdF32voCQw+Hupw4Op92WoZHdIN72e6R6tKmpz1gYjC5oHg3PvlxzSyCBjqcUEPhVLW3g4961QhHYjmX42rWCDhfUp454q0/0WDctmk2Bh4CnYpNBcLtFyihgq5r80tWuGrMe0yrMQEQbXdbbp69P0valtDJFD8PjpXH5s17Yg==
    username: AgDQfpB3kAsmtwF5VTXkI694jTu3rD3CV0als4moKIrALdiEHuru/ckjf3x0RT3/zSMACGBEgR3UOSdTBnIJQox9c5VjQVhAZiM4hpYe9kCMp3s4uZ9D8lGnLvKzrfzPpArPLHU7wuAD9H4y0k4Bm+/XoyFip1Ypd63RFYjxDM3bFvpC+05VZAlanHOhrp/ABBJY24i2tRofbACc4ddqqEc7r/DPdFrJsJH9Dt+I8O8GJ4G8OSmlc7U0+hrAuhdWhJwpZoRIi+nb43rLVAsXI1j14BOcUHHlH8AKShpOPbeB2Ez6qLQRrWz2V6kayHBR24NTE6Rc4gPboetGKUQiDPy570AIbpDv/0xq+RUlHq1H1NO9c6vxdIWYisUoyAgJ3+XLIk6GDouFd8+ZZdFD8/nnHZv/hj6/AMfMhm6nQLoqQURFqYXDtUHyHjs0xjo8NP/HsMX9lt8U92cWgalRx4vvxlMfa/GQOYdjtVH0exUocHROU/Y0fWx36jUEkJ6+FVVhLdaH745TbkGf94G9+q16zjcGnLCWWZDjYUVwKp5Lb8eeBP1Ob6JVOtcpFwUb0XfvlTAw0vqAwRA7SlVaj595ql5tHA/kQVftYzuhVQhzWem8BH7l6RsAQkAlFKa5Zc8bxBuFEVOipR5NQi+HE1/VJ4B6Z4z0A/ExplyYRn4GFHpPDoS+LBOZm6inTxtNuNph9KgrKPPM1A==
  template:
    metadata:
      creationTimestamp: null
      name: gitea-secret
      namespace: gitea
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: runner-secret
  namespace: gitea
spec:
  encryptedData:
    token: AgAyBy0RducqeKC2OqOmeOe5dJC5Z4fi8FnsJw8LvyFqGeBrFHvrj7kWOb1Bst0Mt3yvZ9+QaG3b8jEvQw0XmDwIMaU4XqSj3o8kQDLA6BFgJ/Z0vLnSEilWEBmnJfh8KBBdAoRXk0Ep4v3/EF0hAwFCUkaElv5MNMQkTB7m6Ax/1tN81WMmz/PkZK6tlnsmVD+ZWYPuviGZVZu0rq5j5sJ7asiS1FJ4Tim/GsfTpdcwdM4rETckIkkCQcEt0WO5Own9KB+C66u4Jt6EALkzKk4O1E0WAKnMTxVwyO7BjhDzHW0QNMD3QDLgIaJHmlHGmwUWIApI49JoxZRd+29XjswhAimfNdndZ3/4iaq7y6XHgDkKi5mvKX0/nmW7VY1zk1CnvDCvYjPRHpnmNsAf3f9FT0OYIvJv8FLLQTiFRrx69pU68nXquMFMB+wVvulkmChHKET5VbnddTXWthavXSQKzDyl7qDa+icCl8rGzBkzv+5TNyE5NhjRR9JxBOaKnlRASYouIE+5/5Qy/ZWtlf3webfpCJ+Oy7CpSeYbHczbJqVESz64F9y5d8iwl/wXuddRcEUzdsMMSnbNkiFNzoiTI3AIoD80z3ZW6tHjIcxhJAvv0wj9n578htkmAzW+5YELYhObmQV50gFk+356VuC6mi5RWFTdNCocxL899IzgklrtM9A1lilOqX2PC1sxsHpIAKBOHTZH6b1zK5bwvw66oKIgbGkpbDS9jgyk3Jwrgy8U0OE+xPp7
  template:
    metadata:
      creationTimestamp: null
      name: runner-secret
      namespace: gitea
    type: Opaque
